version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true