apiVersion: v1
kind: Pod
metadata:
  name: apitodolist
  labels:
    name: apitodolist
spec:
  containers:
  - name: apitodolist
    image: higrara/fastapi:apitodolist-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    env:
      - name: BD_PORT
        valueFrom:
          configMapKeyRef:
            name: apitodolist-configmap
            key: BD_PORT
      - name: PORT_REDIS
        valueFrom:
          configMapKeyRef:
            name: apitodolist-configmap
            key: PORT_REDIS
      - name: BD_NAME
        valueFrom:
          secretKeyRef:
            name: apitodolist-secret
            key: BD_NAME
      - name: BD_USER
        valueFrom:
          secretKeyRef:
            name: apitodolist-secret
            key: BD_USER
      - name: BD_HOST
        valueFrom:
          secretKeyRef:
            name: apitodolist-secret
            key: BD_HOST
      - name: BD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: apitodolist-secret
            key: BD_PASSWORD
      - name: HOST_REDIS
        valueFrom:
          secretKeyRef:
            name: apitodolist-secret
            key: HOST_REDIS